### ISSUE TITLE
Adição de páginas oficiais de municípios ao Wikidata

### ISSUE THREAD

**Issue by vgeorge** [mapaslivres/municipios-br#16]
Oi pessoal, fiz um notebook para auxiliar na adição de página oficial dos municípios na Wikidata:

https://beta.observablehq.com/@vgeorge/municipios-do-brasil-sem-pagina-oficial-no-wikidata

Como estamos começando a conectar os dados aqui com a Wikidata, seria legal monitorar a qualidade dos dados por lá também. 

No momento há 4546 municípios sem página definida!

Vejam lá e avisem se tiverem dúvidas.

**Comment by vgeorge** [comment]
Na verdade são 4259 items, antes o notebook estava duplicando municípios com mais de um par de coordenadas.

**Comment by 0e1** [comment]
Mesmo os itens que tem website na wikidata precisam ser verificados. Tem vários errados.
Aqui eu adicionei os websites dos municípios de MT, RS, SP, RJ e PE. Isso dá um 1500 municípios.  Não obtive eles dos itens da wikidata e verifiquei todos eles. Existem formas de adicionar eles na wikidata de maneira automatizada ou semi-automatizada?

**Comment by vgeorge** [comment]
A solução seria criar uma página que compare este repositório com o Wikidata. Aí daria para revisar cada ponto.

**Comment by picsi** [comment]
Talvez um bot que faça isso seria o ideal.

**Comment by vgeorge** [comment]
Entendo que a atividade de adicionar websites ao municípios deve ser coordenada no contexto da comunidade Wikidata. O notebook foi adicionar ao README deste repositório para as pessoas interessadas em usar/editar estes dados. No momento há ~3400 municípios a completar.
